# Generated by Django 2.2.28 on 2022-05-01 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multilingual_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'tag Translation'},
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_items', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='multilingual_tags.Tag'),
        ),
    ]
